#Version del docker compose
version: "3.3"

services:
    node-ticketservicios:
        image: $DEPLOY_TAG
        container_name: $BUILD_TAG
        restart: always
        ports:   
            - $APP_PORT:$APP_PORT
        networks:
            - webnet            
        volumes: 
            - subidos:/uploads
        environment:
            - MYSQL_SERVER=$MYSQL_SERVER
            - MYSQL_PORT=$MYSQL_PORT
            - MYSQL_DB=$MYSQL_DB
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PW=$MYSQL_PW
            # si se necesita trabajar con la base de datos local solo cambiar el valor de la variable DEPLOYMENT, no borrarla
            - APP_PORT=$APP_PORT

volumes:
    subidos:
        external: true
                
networks:
    webnet:            